name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Setup actionLint
        uses: KeisukeYamashita/setup-release@v1
        with:
          repository: rhysd/actionlint
      - name: Install dependencies
        run: npm ci
      - uses: actions/setup-python@v2
      - name: Pre-commit
        uses: pre-commit/action@v2.0.0
