name: Release
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install actionlint
        uses: open-turo/action-install-release@v1
        with:
          repository: rhysd/actionlint
      - name: Install dependencies
        run: npm ci
      - uses: actions/setup-python@v2
      - name: Pre-commit
        uses: pre-commit/action@v2.0.0

  release:
    name: Release
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install actionlint
        uses: open-turo/action-install-release@v1
        with:
          repository: rhysd/actionlint
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            semantic-release-github-pullrequest
        env:
          GITHUB_TOKEN: ${{ secrets.OPEN_TURO_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.OPEN_TURO_NPM_TOKEN }}
